# ItemLimiter Config
# Limits are saved here.

# Format: MATERIAL: AMOUNT
limits:
  TOTEM_OF_UNDYING: 1
  ENCHANTED_GOLDEN_APPLE: 6

# List of worlds where limits are active.
# Leave empty [] to activate everywhere.
enabled-worlds: []
#  - "world"
#  - "farmworld"

# Limit specific potions or arrows by using MATERIAL:POTION_TYPE
# 0 means completely blocked!
  POTION:STRONG_HARMING: 0
  SPLASH_POTION:STRONG_HARMING: 0
  LINGERING_POTION:STRONG_HARMING: 0
  TIPPED_ARROW:STRONG_HARMING: 0
  POTION:HARMING: 1
