# ItemLimiter Config
# Limits are saved here.

# Format: MATERIAL: AMOUNT
limits:
  TOTEM_OF_UNDYING: 1
  ENCHANTED_GOLDEN_APPLE: 6

# List of worlds where limits are active.
# Leave empty [] to activate everywhere.
enabled-worlds: []
#  - "world"
#  - "farmworld"

# Limit specific potions (0 to block completely)
potion-limits:
  STRONG_HARMING: 0
  HARMING: 1

# Limit specific tipped arrows (0 to block completely)
arrow-limits:
  STRONG_HARMING: 0
